### ISSUE TITLE
Trade request

### ISSUE THREAD

**Issue by zacons** [simplecrypto/simplecoin_rpc_client#9]
Hi
I know this is not a forum but I'm trying to figure out about all those trade requested and how to create them. Furthermore I'd be interessed to know if there is still dev going on esp. for single currency payout or if someone has code to share or sell.

thanks and sorry for abusing github for this

**Comment by ericecook** [comment]
Hello,

Trade requests are created by SCM (https://github.com/simplecrypto/simplecoin_multi). Payout procedure is outlined in the readme. Not much dev is going on with this - but we do try to keep up with ops/dev questions at the mailing list (https://groups.google.com/forum/#!forum/simplecrypto-dev)
